/**
 * Handwritten wire types for the workbench backend API.
 *
 * This file is the single handwritten contract surface (AGENTS.md): every
 * type here mirrors a schema in `backend/app/api/schemas.py`, and the pinned
 * OpenAPI file next to it (`openapi.json`, regenerated by
 * `uv run python -m app.openapi`) is checked against this file by
 * `tests/contracts.spec.ts` and against the live app by
 * `backend/tests/test_openapi_contract.py`. Keep both sides in one commit.
 */

/** `POST /api/projects` request. */
export interface CreateProjectRequest {
  readonly name: string
  /** Client-generated id; the same id always returns the same project. */
  readonly requestId: string
}

/** `PATCH /api/projects/{id}/workspace` request. */
export interface BindWorkspaceRequest {
  readonly workspaceId: string
}

/** One registered project (wire shape: `backend/app/api/schemas.py::ProjectOut`). */
export interface ProjectRecord {
  readonly id: string
  readonly name: string
  /** Managed directory, allocated by the backend. */
  readonly directory: string
  /** DSH workspace id; null until the workspace binding step succeeds. */
  readonly workspaceId: string | null
  readonly createdAt: string
  readonly updatedAt: string
}

/** `GET /api/projects` response. */
export interface ProjectList {
  readonly projects: readonly ProjectRecord[]
}

/** `GET /api/health` response. */
export interface Health {
  readonly status: string
}
