import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { pdfFixture } from '../pdf-fixture';
test('workspace, paper, directory import, PDF reading, Pi editing, conversations and reconnect', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await page.getByRole('button', { name: '新建工作区', exact: true }).click();
  await page.getByLabel('名称', { exact: true }).fill('可复现研究'); await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page).toHaveURL(/\/workspaces\//); const workspaceId = new URL(page.url()).pathname.split('/').pop()!;
  await page.getByRole('button', { name: '新建论文', exact: true }).click(); await page.getByLabel('名称', { exact: true }).fill('一个完整的论文工程'); await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByRole('button', { name: '一个完整的论文工程', exact: true })).toBeVisible();
  const papers = await (await request.get(`/api/workspaces/${workspaceId}/papers`)).json(); const paperId = papers[0].id as string;
  await page.getByRole('button', { name: '导入材料', exact: true }).click();
  await page.getByLabel('选择材料文件').setInputFiles({ name: 'article.pdf', mimeType: 'application/pdf', buffer: pdfFixture() });
  await page.getByRole('button', { name: '导入', exact: true }).click();
  await page.getByRole('button', { name: 'article.pdf', exact: true }).click();
  await expect(page.locator('.textLayer')).toContainText('Research fixture');
  expect(await page.locator('.reader-panel canvas').evaluate(canvas => (canvas as HTMLCanvasElement).width)).toBeGreaterThan(0);
  const imported = await request.post(`/api/workspaces/${workspaceId}/imports`, { multipart: { metadata: JSON.stringify({ requestId: randomUUID(), target: `papers/${paperId}`, folderName: 'source' }), first: { name: 'main.tex', mimeType: 'text/plain', buffer: Buffer.from('\\input{sections/body.tex}') }, second: { name: 'sections/body.tex', mimeType: 'text/plain', buffer: Buffer.from('A reproducible result.') } } });
  expect(imported.status()).toBe(201);
  await page.getByRole('button', { name: '刷新文件', exact: true }).click(); await page.getByRole('button', { name: 'source', exact: true }).click(); await page.getByRole('button', { name: 'main.tex', exact: true }).click();
  await expect(page.locator('.text-preview')).toContainText('sections/body.tex');
  const note = await request.post(`/api/workspaces/${workspaceId}/imports`, { multipart: { metadata: JSON.stringify({ requestId: randomUUID(), target: '' }), file: { name: 'note.txt', mimeType: 'text/plain', buffer: Buffer.from('alpha') } } }); expect(note.status()).toBe(201);
  await page.getByRole('button', { name: '新建对话', exact: true }).click(); await page.getByLabel('名称', { exact: true }).fill('讨论 A'); await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByLabel('选择模型').selectOption('test/test-model');
  await page.getByRole('button', { name: '将当前材料加入对话', exact: true }).click(); await expect(page.locator('.material-chip')).toContainText('main.tex');
  await page.getByLabel('对话消息').fill('[EDIT]'); await page.getByRole('button', { name: '发送消息', exact: true }).click();
  await expect(page.locator('.conversation-messages')).toContainText('已读取并修改 note.txt');
  expect((await (await request.get(`/api/workspaces/${workspaceId}/file?path=note.txt&format=text`)).json()).text).toBe('beta');
  await page.getByRole('button', { name: '新建对话', exact: true }).click(); await page.getByLabel('名称', { exact: true }).fill('讨论 B'); await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByRole('tab', { name: '讨论 B', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByLabel('对话消息').fill('[SLOW]'); await page.getByRole('button', { name: '发送消息', exact: true }).click(); await expect(page.locator('.conversation-messages')).toContainText('片段');
  await page.reload(); await expect(page.getByRole('button', { name: '停止回答', exact: true })).toBeVisible(); await page.getByRole('button', { name: '停止回答', exact: true }).click(); await expect(page.getByRole('button', { name: '停止回答', exact: true })).not.toBeVisible();
  await page.getByRole('tab', { name: '讨论 A', exact: true }).click(); await expect(page.locator('.conversation-messages')).toContainText('已读取并修改 note.txt');
  await page.getByRole('button', { name: 'article.pdf', exact: true }).click(); await expect(page.locator('.textLayer')).toContainText('Research fixture');
  await mkdir('.tools/screenshots', { recursive: true }); await page.screenshot({ path: '.tools/screenshots/workbench-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole('button', { name: '阅读', exact: true }).click(); await expect(page.locator('.reader-panel')).toBeVisible();
  await page.screenshot({ path: '.tools/screenshots/workbench-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
